-- create databse hbtn_0d_usa & table states
-- states description id, name
-- id is unique, autogenerated, primary key, not null, INT
-- name can't be null
-- script should not fail
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa
CREATE TABLE IF NOT EXISTS states (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(256) NOT NULL
);
